// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package treadmark

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName      *string           `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name"`
	PackerBuilderType    *string           `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type"`
	PackerCoreVersion    *string           `mapstructure:"packer_core_version" cty:"packer_core_version" hcl:"packer_core_version"`
	PackerDebug          *bool             `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug"`
	PackerForce          *bool             `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force"`
	PackerOnError        *string           `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error"`
	PackerUserVars       map[string]string `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables"`
	PackerSensitiveVars  []string          `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables"`
	Mode                 *string           `mapstructure:"mode" cty:"mode" hcl:"mode"`
	OutputDir            *string           `mapstructure:"output_dir" cty:"output_dir" hcl:"output_dir"`
	AllowMissingBaseline *bool             `mapstructure:"allow_missing_baseline" cty:"allow_missing_baseline" hcl:"allow_missing_baseline"`
	ImagePath            *string           `mapstructure:"image_path" cty:"image_path" hcl:"image_path"`
	ConfigSource         *string           `mapstructure:"config_source" cty:"config_source" hcl:"config_source"`
	TreadmarkBinary      *string           `mapstructure:"treadmark_binary" cty:"treadmark_binary" hcl:"treadmark_binary"`
	OfflineStrategy      *string           `mapstructure:"offline_strategy" cty:"offline_strategy" hcl:"offline_strategy"`
	LibguestfsBackend    *string           `mapstructure:"libguestfs_backend" cty:"libguestfs_backend" hcl:"libguestfs_backend"`
	ExtraEnv             map[string]string `mapstructure:"extra_env" cty:"extra_env" hcl:"extra_env"`
	UseSudo              *bool             `mapstructure:"use_sudo" cty:"use_sudo" hcl:"use_sudo"`
	MountTimeout         *string           `mapstructure:"mount_timeout" cty:"mount_timeout" hcl:"mount_timeout"`
	InitTimeout          *string           `mapstructure:"init_timeout" cty:"init_timeout" hcl:"init_timeout"`
	SkipVerify           *bool             `mapstructure:"skip_verify" cty:"skip_verify" hcl:"skip_verify"`
	OnDrift              *string           `mapstructure:"on_drift" cty:"on_drift" hcl:"on_drift"`
	ReportFormats        []string          `mapstructure:"report_formats" cty:"report_formats" hcl:"report_formats"`
	Metadata             map[string]string `mapstructure:"metadata" cty:"metadata" hcl:"metadata"`
	S3                   []FlatS3Config    `mapstructure:"s3" cty:"s3" hcl:"s3"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"packer_build_name":          &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"packer_builder_type":        &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"packer_core_version":        &hcldec.AttrSpec{Name: "packer_core_version", Type: cty.String, Required: false},
		"packer_debug":               &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"packer_force":               &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"packer_on_error":            &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"packer_user_variables":      &hcldec.AttrSpec{Name: "packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"packer_sensitive_variables": &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"mode":                       &hcldec.AttrSpec{Name: "mode", Type: cty.String, Required: false},
		"output_dir":                 &hcldec.AttrSpec{Name: "output_dir", Type: cty.String, Required: false},
		"allow_missing_baseline":     &hcldec.AttrSpec{Name: "allow_missing_baseline", Type: cty.Bool, Required: false},
		"image_path":                 &hcldec.AttrSpec{Name: "image_path", Type: cty.String, Required: false},
		"config_source":              &hcldec.AttrSpec{Name: "config_source", Type: cty.String, Required: false},
		"treadmark_binary":           &hcldec.AttrSpec{Name: "treadmark_binary", Type: cty.String, Required: false},
		"offline_strategy":           &hcldec.AttrSpec{Name: "offline_strategy", Type: cty.String, Required: false},
		"libguestfs_backend":         &hcldec.AttrSpec{Name: "libguestfs_backend", Type: cty.String, Required: false},
		"extra_env":                  &hcldec.AttrSpec{Name: "extra_env", Type: cty.Map(cty.String), Required: false},
		"use_sudo":                   &hcldec.AttrSpec{Name: "use_sudo", Type: cty.Bool, Required: false},
		"mount_timeout":              &hcldec.AttrSpec{Name: "mount_timeout", Type: cty.String, Required: false},
		"init_timeout":               &hcldec.AttrSpec{Name: "init_timeout", Type: cty.String, Required: false},
		"skip_verify":                &hcldec.AttrSpec{Name: "skip_verify", Type: cty.Bool, Required: false},
		"on_drift":                   &hcldec.AttrSpec{Name: "on_drift", Type: cty.String, Required: false},
		"report_formats":             &hcldec.AttrSpec{Name: "report_formats", Type: cty.List(cty.String), Required: false},
		"metadata":                   &hcldec.AttrSpec{Name: "metadata", Type: cty.Map(cty.String), Required: false},
		"s3":                         &hcldec.BlockListSpec{TypeName: "s3", Nested: hcldec.ObjectSpec((*FlatS3Config)(nil).HCL2Spec())},
	}
	return s
}

// FlatS3Config is an auto-generated flat version of S3Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatS3Config struct {
	Bucket         *string `mapstructure:"bucket" required:"true" cty:"bucket" hcl:"bucket"`
	Prefix         *string `mapstructure:"prefix" cty:"prefix" hcl:"prefix"`
	Region         *string `mapstructure:"region" cty:"region" hcl:"region"`
	Endpoint       *string `mapstructure:"endpoint" cty:"endpoint" hcl:"endpoint"`
	ForcePathStyle *bool   `mapstructure:"force_path_style" cty:"force_path_style" hcl:"force_path_style"`
	StorageClass   *string `mapstructure:"storage_class" cty:"storage_class" hcl:"storage_class"`
	SSE            *string `mapstructure:"sse" cty:"sse" hcl:"sse"`
	KMSKeyID       *string `mapstructure:"kms_key_id" cty:"kms_key_id" hcl:"kms_key_id"`
	IncludeImage   *bool   `mapstructure:"include_image" cty:"include_image" hcl:"include_image"`
}

// FlatMapstructure returns a new FlatS3Config.
// FlatS3Config is an auto-generated flat version of S3Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*S3Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatS3Config)
}

// HCL2Spec returns the hcl spec of a S3Config.
// This spec is used by HCL to read the fields of S3Config.
// The decoded values from this spec will then be applied to a FlatS3Config.
func (*FlatS3Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"bucket":           &hcldec.AttrSpec{Name: "bucket", Type: cty.String, Required: false},
		"prefix":           &hcldec.AttrSpec{Name: "prefix", Type: cty.String, Required: false},
		"region":           &hcldec.AttrSpec{Name: "region", Type: cty.String, Required: false},
		"endpoint":         &hcldec.AttrSpec{Name: "endpoint", Type: cty.String, Required: false},
		"force_path_style": &hcldec.AttrSpec{Name: "force_path_style", Type: cty.Bool, Required: false},
		"storage_class":    &hcldec.AttrSpec{Name: "storage_class", Type: cty.String, Required: false},
		"sse":              &hcldec.AttrSpec{Name: "sse", Type: cty.String, Required: false},
		"kms_key_id":       &hcldec.AttrSpec{Name: "kms_key_id", Type: cty.String, Required: false},
		"include_image":    &hcldec.AttrSpec{Name: "include_image", Type: cty.Bool, Required: false},
	}
	return s
}
