// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package treadmark

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName       *string           `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name"`
	PackerBuilderType     *string           `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type"`
	PackerCoreVersion     *string           `mapstructure:"packer_core_version" cty:"packer_core_version" hcl:"packer_core_version"`
	PackerDebug           *bool             `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug"`
	PackerForce           *bool             `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force"`
	PackerOnError         *string           `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error"`
	PackerUserVars        map[string]string `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables"`
	PackerSensitiveVars   []string          `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables"`
	OS                    *string           `mapstructure:"os" cty:"os" hcl:"os"`
	Arch                  *string           `mapstructure:"arch" cty:"arch" hcl:"arch"`
	InstallMethod         *string           `mapstructure:"install_method" cty:"install_method" hcl:"install_method"`
	TreadmarkVersion      *string           `mapstructure:"treadmark_version" cty:"treadmark_version" hcl:"treadmark_version"`
	PackagePath           *string           `mapstructure:"package_path" cty:"package_path" hcl:"package_path"`
	DownloadURLBase       *string           `mapstructure:"download_url_base" cty:"download_url_base" hcl:"download_url_base"`
	DisableChecksumVerify *bool             `mapstructure:"disable_checksum_verify" cty:"disable_checksum_verify" hcl:"disable_checksum_verify"`
	TreadmarkPath         *string           `mapstructure:"treadmark_path" cty:"treadmark_path" hcl:"treadmark_path"`
	ConfigPath            *string           `mapstructure:"config_path" cty:"config_path" hcl:"config_path"`
	ConfigSource          *string           `mapstructure:"config_source" cty:"config_source" hcl:"config_source"`
	Scope                 *string           `mapstructure:"scope" cty:"scope" hcl:"scope"`
	SkipVerify            *bool             `mapstructure:"skip_verify" cty:"skip_verify" hcl:"skip_verify"`
	OnDrift               *string           `mapstructure:"on_drift" cty:"on_drift" hcl:"on_drift"`
	ReportFormats         []string          `mapstructure:"report_formats" cty:"report_formats" hcl:"report_formats"`
	SkipDownload          *bool             `mapstructure:"skip_download" cty:"skip_download" hcl:"skip_download"`
	OutputDir             *string           `mapstructure:"output_dir" cty:"output_dir" hcl:"output_dir"`
	RemoveFromImage       *bool             `mapstructure:"remove_from_image" cty:"remove_from_image" hcl:"remove_from_image"`
	DisableSudo           *bool             `mapstructure:"disable_sudo" cty:"disable_sudo" hcl:"disable_sudo"`
	StagingDir            *string           `mapstructure:"staging_dir" cty:"staging_dir" hcl:"staging_dir"`
	InitTimeout           *string           `mapstructure:"init_timeout" cty:"init_timeout" hcl:"init_timeout"`
	Metadata              map[string]string `mapstructure:"metadata" cty:"metadata" hcl:"metadata"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"packer_build_name":          &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"packer_builder_type":        &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"packer_core_version":        &hcldec.AttrSpec{Name: "packer_core_version", Type: cty.String, Required: false},
		"packer_debug":               &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"packer_force":               &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"packer_on_error":            &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"packer_user_variables":      &hcldec.AttrSpec{Name: "packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"packer_sensitive_variables": &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"os":                         &hcldec.AttrSpec{Name: "os", Type: cty.String, Required: false},
		"arch":                       &hcldec.AttrSpec{Name: "arch", Type: cty.String, Required: false},
		"install_method":             &hcldec.AttrSpec{Name: "install_method", Type: cty.String, Required: false},
		"treadmark_version":          &hcldec.AttrSpec{Name: "treadmark_version", Type: cty.String, Required: false},
		"package_path":               &hcldec.AttrSpec{Name: "package_path", Type: cty.String, Required: false},
		"download_url_base":          &hcldec.AttrSpec{Name: "download_url_base", Type: cty.String, Required: false},
		"disable_checksum_verify":    &hcldec.AttrSpec{Name: "disable_checksum_verify", Type: cty.Bool, Required: false},
		"treadmark_path":             &hcldec.AttrSpec{Name: "treadmark_path", Type: cty.String, Required: false},
		"config_path":                &hcldec.AttrSpec{Name: "config_path", Type: cty.String, Required: false},
		"config_source":              &hcldec.AttrSpec{Name: "config_source", Type: cty.String, Required: false},
		"scope":                      &hcldec.AttrSpec{Name: "scope", Type: cty.String, Required: false},
		"skip_verify":                &hcldec.AttrSpec{Name: "skip_verify", Type: cty.Bool, Required: false},
		"on_drift":                   &hcldec.AttrSpec{Name: "on_drift", Type: cty.String, Required: false},
		"report_formats":             &hcldec.AttrSpec{Name: "report_formats", Type: cty.List(cty.String), Required: false},
		"skip_download":              &hcldec.AttrSpec{Name: "skip_download", Type: cty.Bool, Required: false},
		"output_dir":                 &hcldec.AttrSpec{Name: "output_dir", Type: cty.String, Required: false},
		"remove_from_image":          &hcldec.AttrSpec{Name: "remove_from_image", Type: cty.Bool, Required: false},
		"disable_sudo":               &hcldec.AttrSpec{Name: "disable_sudo", Type: cty.Bool, Required: false},
		"staging_dir":                &hcldec.AttrSpec{Name: "staging_dir", Type: cty.String, Required: false},
		"init_timeout":               &hcldec.AttrSpec{Name: "init_timeout", Type: cty.String, Required: false},
		"metadata":                   &hcldec.AttrSpec{Name: "metadata", Type: cty.Map(cty.String), Required: false},
	}
	return s
}
